Stabilize tests/gps/test_views.py::test_beneficiary_details
The department is used to decide whether to enable the feature.

```diff
FAILED tests/gps/test_views.py::test_beneficiary_details - assert [+ received] == [- snapshot]
    '''
                        ...
                                            <div class="c-info c-info--secondary" id="advisor-info-details-collapsable">
  -                                             <button aria-controls="collapseAdvisorInfoDetails" aria-expanded="false" class="c-info__summary collapsed" data-bs-target="#collapseAdvisorInfoDetails" data-bs-toggle="collapse" data-matomo-action="clic" data-matomo-category="gps" data-matomo-event="true" data-matomo-option="coordonnees-conseiller-ailleurs">
  +                                             <button aria-controls="collapseAdvisorInfoDetails" aria-expanded="false" class="c-info__summary collapsed" data-bs-target="#collapseAdvisorInfoDetails" data-bs-toggle="collapse" data-matomo-action="clic" data-matomo-category="gps" data-matomo-event="true" data-matomo-option="coordonnees-conseiller-55">
                                                    <span>Voir les coordonnées du
                                                    ...

  -                                                     <p class="mb-0">
  +                                                     <p class="mb-0">Le conseiller emploi France Travail de ce bénéficiaire n’est pas connu.</p>
  -                                                         La fonctionnalité est en test dans deux départements et sera bientôt disponible pour votre territoire.
  -                                                     </p>

                            ...
    '''
```