www: Fix handling of non-empty query string RedirectToNewDomainMiddleware
`QueryDict` expects a string or bytestring as its first argument.
Passing an empty `QueryDict` worked, because there was a truthiness
check that short-circuited the initialization. But passing a non-empty
one raised an error:

      File "/path/.venv/lib/python3.13/site-packages/django/http/request.py", line 592, in __init__
        for key, value in parse_qsl(query_string, **parse_qsl_kwargs):
                          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/path/.local/share/uv/python/cpython-3.13.12-linux-x86_64-gnu/lib/python3.13/urllib/parse.py", line 800, in parse_qsl
        qs = bytes(memoryview(qs))
                   ~~~~~~~~~~^^^^
    TypeError: memoryview: a bytes-like object is required, not 'dict'