cron: disable sync_cities
It currently fails on delete with:

    django.db.models.deletion.RestrictedError: ("Cannot delete some
    instances of model 'City' because they are referenced through
    restricted foreign keys: 'Company.insee_city',
    'JobDescription.location', 'User.insee_city',
    'PrescriberOrganization.insee_city'.", {<User: ...

and tends to print personal information to our logs