DO NOT USE DIRECTLY: Use the master version of build files
git checkout master -- Makefile .github/ scripts/

Sentry got filled with:
ConfigurationError: huey.consumer in start

Consumer cannot be run with Huey instances where immediate is enabled.
Please check your configuration and ensure that "huey.immediate =
False".

The issue is likely caused by 8186cb2c1380502962f3f28de4f5285555303cf7.
If ever deploying this branch again, fix it instead of burning Sentry
credits.

https://itou.sentry.io/issues/6033541217/