Fix flaky tests about capitalization Capitalize first name and last name with the `title()` method when they are used with `capfirst` in the email templates.
Flaky error observed on my local dev:

======================================================================
FAIL: test_email_invitation (itou.invitations.tests.TestSiaeInvitationEmails)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/app/itou/invitations/tests.py", line 218, in test_email_invitation
    self.assertIn(invitation.first_name, email.body)
  File "/usr/local/lib/python3.7/unittest/case.py", line 1119, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/local/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: 'daisy' not found in "Bonjour Daisy Herve !
[...]