Use citext plugin for the email fields
CICharField, CITextField and CIEmailField will soon be removed from
Django. The project recommends using a collation instead.

While the advice makes a lot of sense for CICharField and CITextField,
which contain text that is usually represented with unicode, it isn’t as
good for CIEmailField. Emails aren’t just text, they follow a
specification [1], especially the addr-spec part that has a pretty
narrow range of characters.

Having a collation for emails apply specifying the collation for the
index, and for *each* request, including from third-party libraries.

Replacing CIEmailField with a functional index for `UPPER()` [2] has
been considered. Léo suggested maybe using custom lookups to force use
of icontains, iexact, etc. [4]. It could have been implemented as a
subclass of EmailField (e.g. IndexedEmailField) to ensure the transform
was always applied.

Starting down this path, the following issues were encountered:

1. `django-allauth` decided to use `LOWER` for its emails [3]
2. PostgreSQL doesn’t support mapping a function to all values in an
   ARRAY before creating a GIN index. That means the Email.{to,cc,bcc}
   fields could not be indexed. [5]

Eventually, `citext` has been ported as a third-party library with
company support. It’s the simplest alternative to ignoring character
casing in emails, and has worked well for this project for 5 years.
Let’s keep using CIEmailField.

See the discussion on django-developers:
https://groups.google.com/g/django-developers/c/nDMnO98nexY/m/fyY2J-5gAgAJ

---

[1] https://www.rfc-editor.org/rfc/rfc5322#section-3.4.1

[2] django utilise UPPER : https://github.com/django/django/blob/f812b927a541fecc8ee445e1fd4dbe9d0540d523/django/db/backends/postgresql/base.py#L154-L167

[3] https://github.com/pennersr/django-allauth/blob/701ef63cfd4508af0faf0671ac89c87e0d52a801/allauth/account/utils.py#L448-L487

[4] Registering custom lookups:

```python
In [1]: from itou.users.models import User

In [2]: from django.db.models import EmailField, lookups

In [3]: str(User.objects.only("email").filter(email__contains="leo").query)
Out[3]: 'SELECT "users_user"."id", "users_user"."email" FROM "users_user" WHERE "users_user"."email"::citext LIKE %leo%'

In [4]: EmailField.register_lookup(lookups.IContains, "contains")
Out[4]: django.db.models.lookups.IContains

In [5]: str(User.objects.only("email").filter(email__contains="leo").query)
Out[5]: 'SELECT "users_user"."id", "users_user"."email" FROM "users_user" WHERE UPPER("users_user"."email"::citext) LIKE UPPER(%leo%)'
```

[5] Applying UPPER on all values of an ARRAY for a GIN index:

```sql
itou=# CREATE INDEX ON emails_email USING GIN (UPPER(UNNEST("to")));
ERROR:  set-returning functions are not allowed in index expressions
```