Handle missing anymail attributes on emails
In the development environment, emails are not sent through Anymail and
not annotated with an `anymail_status` attribute, resulting in
exceptions when accessing the attribute during the Huey task execution.

Example error:
```
Unhandled exception in task 8d557b55-0a22-4437-9134-4aa7986a7316.
Traceback (most recent call last):
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/huey/api.py", line 382, in _execute
    task_value = task.execute()
                 ^^^^^^^^^^^^^^
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/utils.py", line 1711, in runner
    return sentry_patched_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/huey.py", line 130, in _sentry_execute
    reraise(*exc_info)
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/utils.py", line 1640, in reraise
    raise value
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/huey.py", line 126, in _sentry_execute
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freitafr/dev/itou/.venv/lib/python3.11/site-packages/huey/api.py", line 807, in execute
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freitafr/dev/itou/itou/utils/tasks.py", line 131, in _async_send_message
    esp_response = email.anymail_status.esp_response.json()
                   ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'EmailMessage' object has no attribute 'anymail_status'
```