fix a flacky test due to a user_pk collision
test_change_asp_uid needs two users: a superadmin for the admin_client
object, and a profile from FactoryBoy.

Happened to me that the superadmin got the user_id 42, blocking the
creation of the profile by FactoryBoy, leading to test failure:

django.core.exceptions.ValidationError: {'id': ['Un objet Utilisateur avec ce champ ID existe déjà.']}